spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/university_db
    username: university
    password: 1111
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /university
  port: 8080

university:
  courseNames:
    - Mathematics
    - Biology
    - Geography
    - Chemistry
    - Physics
    - Astronomy
    - Literature
    - English
    - Sports
    - Music
    - Music1
    - Music2
  firstNames:
    - Liam
    - Olivia
    - Noah
    - Emma
    - Oliver
    - Charlotte
    - James
    - Amelia
    - Elijah
    - Sophia
    - William
    - Isabella
    - Henry
    - Ava
    - Lucas
    - Mia
    - Benjamin
    - Evelyn
    - Theodore
    - Luna
  lastNames:
    - Smith
    - Johnson
    - Williams
    - Brown
    - Jones
    - Garcia
    - Miller
    - Davis
    - Wilson
    - Anderson
    - Thomas
    - Taylor
    - Moore
    - Lee
    - Thompson
    - Clark
    - White
    - Walker
    - Robinson
    - Torres
  groupsLimit : 4
  groupsCount : 5
  loginSize: 6
  passwordSize: 8
  passwordSymbolLimit: 9
  studentsCount: 200
  teachersCount: 12
  adminFirstName: admin
  adminLastName: admin
isDebug: true